### ISSUE TITLE
Question: Future plans

### ISSUE THREAD

**Issue by JeffreyPerplex** [Offroadcode/Umbraco-2FA#7]
I'm wondering what are your future plans with this package. I've been working on stuff like this too and made a mock-up two years ago (http://umbraco.usermanagement.perplex.eu/logon.html) for a Skrift article I wrote (http://skrift.io/articles/archive/i-have-a-dream-about-user-management-in-umbraco/). Also I know that Umbraco HQ is working on stuff for Umbraco 7.7 (https://our.umbraco.org/contribute/releases/770) where it's drastically improving the User-section.

In your code I see a table called FortressLoginEvents and FortressFirewallEntry and I can take some sort of a guess what it will do, but I'm wondering if you've got any planning or ideas that you would like to share.

Thanks,

Jeffrey

**Comment by PeteDuncanson** [comment]
Hi Jeffery,

We originally build this as sort of a one stop shop for all our security stuff hence all the legacy stuff you see in the code base. We are stripping all that right back so this one just focuses on the 2FA part (which is the bit everyone wants). Other packages have come out since which sort of cover the other areas we originally had in here. Future wise we'll make this solely focused on 2FA however we expect this to eventually be pulled into core at some point. This package can act as a bridge until that happens I guess.

Cheers

Pete
